### ISSUE TITLE
Definition of plant area density and plant area index

### ISSUE THREAD

**Issue by han16nah** [umr-amap/AMAPVox#6]
Hi,

I am working with simulated UAV-based laser scanning data and am estimating the leaf area index/leaf area with AMAPVox. Working with virtual laser scanning means that I have "perfect" reference leaf area available from the mesh model that serves as input for my laser scanning simulations. These reference leaf area values are defined as the **one-sided leaf area**. 

My issue is that when comparing the reference values with AMAPVox output, AMAPVox is around 2x higher. Now I'm wondering if there is a difference in definition, i.e., does AMAPVox define the leaf area as the **two-sided leaf area** (or the plant area as the total area instead of half of the area). Can this explain the discrepancies between my reference and the AMAPVox values?

Best wishes,

Hannah

**Comment by GregoireVincent** [comment]
Hi Hannah,
AMAPVox also uses the standard one-sided definition for leaf area so this is not why you are finding apparently insconsistent estimates of PAD. 
Please first note that PAD would include woody elements but that wood area is not unequivocally defined in the literature. So if you have access within your simulation to leaf contribution (i.e. you can classify returns as either leaf or wood) you could probably build a more stringent test (not sure what is your aim here). 
Having said that AMAPvox will produce an estimate of PAD/LAD using certain asumptions which you might want to review (leaf inclination distribution function, mean leaf size) to check that they are met in your simulation. Voxel size and locally poor sampling can also both affect the final PAD/LAD estimate. So it is difficult without additional info to be specific about what may cause the pattern you describe.
Finally, I suppose you are using Helios to simulate the UAV point cloud. If you have adjusted the parameters to mimic observed real world scanning patterns and notably standard number of returns per pulse you may be experiencing the effect of censorship. You can have a look at the paper attached which explains the issue. We have conducted additionnal tests using high power ALS since the paper was printed and the picture is even more vivid now. I believe that in some cases, this censorship bias may indeed lead to a factor of 2 overestimation of LAD/PAD. If you are interested we can discuss more about the issue. 
[VincentEtAl2023_RSE.pdf](https://github.com/umr-amap/AMAPVox/files/11334133/VincentEtAl2023_RSE.pdf)
Best regards,
Greg

**Comment by han16nah** [comment]
Hi @GregoireVincent,
thanks for the clarification.
I am using only leaf points for the leaf area estimation and as I am only interested in total (one-sided) leaf area, I am simply summing all PAD values and multiplying by voxel volume. I tuned a couple of parameters (esp. voxel size), and specified the leaf angle distribution (I had it at the default spherical before). I am now getting reasonable results 👍 
I will also have a look at the RSE paper you sent and the censorship bias you describe.
